stages:
  - lint

eslint:
  image: 14.17.6-alpine
  stage: lint
  script:
    - npm install
    - npm run lint

prettier:
  image: 14.17.6-alpine
  stage: lint
  script:
    - npm install
    - npm run check:format
