name: lint
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  eslint:
    runs-on: ubuntu-latest
    container:
      image: node:14.17.6-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Lint source code with ESLint
        run: npm run lint
