name: eslint
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm install
      - name: Lint source code with ESLint
        run: npm run lint
