name: lint

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: node:14.17.6
    steps:
      - uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: Install dependencies
        run: npm ci --ignore-scripts

  eslint:
    name: ESLint
    needs: build
    runs-on: ubuntu-latest
    container:
      image: node:14.17.6
    steps:
      - uses: actions/checkout@v2
      - name: Cache node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: Lint source code with ESLint
        run: npm run lint

  prettier:
    name: Prettier
    needs: build
    runs-on: ubuntu-latest
    container:
      image: node:14.17.6
    steps:
      - uses: actions/checkout@v2
      - name: Cache node.js modules
        uses: actions/cache@v2
        env:
          cache-name: npm-${{ hashFiles('package-lock.json') }}
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: Lint source code with Prettier
        run: npm run check:format
